// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DoAfterController from "./do_after_controller.js"
application.register("do-after", DoAfterController)

import RemoverController from "./remover_controller.js"
application.register("remover", RemoverController)

import ToggleController from "./toggle_controller.js"
application.register("toggle", ToggleController)
