export const search: string;
export const navbarItem: string;
export const input: string;
export const form: string;
export const searchInput: string;
export const header: string;
export const title: string;
export const query: string;
export const key: string;
