# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe Admin::ApplicationsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Doorkeeper::Application. As you add validations to Doorkeeper::Application, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      name: "test",
      redirect_uri: "https://localhost.local",
      official: false
    }
  end

  let(:invalid_attributes) do
    {
      redirect_uri: "non-absolute"
    }
  end

  let(:user) { create :user, :with_permissions, permissions: [] }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Doorkeeper::ApplicationsController. Be sure to keep this updated too.
  let(:valid_session) do
    {
      user_id: user.id
    }
  end

  describe "GET #index" do
    it "returns a success response" do
      Doorkeeper::Application.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      application = Doorkeeper::Application.create! valid_attributes
      get :show, params: { id: application.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      application = Doorkeeper::Application.create! valid_attributes
      get :edit, params: { id: application.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) do
        {
          name: "fred",
          official: true
        }
      end

      it "updates the requested application successfully" do
        application = Doorkeeper::Application.create! valid_attributes
        put :update, params: { id: application.to_param, application: new_attributes }, session: valid_session

        expect(response).to redirect_to(admin_application_path(application))
      end

      it "updates the requested applications name" do
        application = Doorkeeper::Application.create! valid_attributes
        put :update, params: { id: application.to_param, application: new_attributes }, session: valid_session
        application.reload

        expect(application.name).to eq(new_attributes[:name])
      end

      it "redirects to the application" do
        application = Doorkeeper::Application.create! valid_attributes
        put :update, params: { id: application.to_param, application: valid_attributes }, session: valid_session

        expect(response).to redirect_to(admin_application_path(application))
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        application = Doorkeeper::Application.create! valid_attributes
        put :update, params: { id: application.to_param, application: invalid_attributes }, session: valid_session

        expect(response).to be_successful
      end

      it "doesn't set the invalid redirect_uri" do
        application = Doorkeeper::Application.create! valid_attributes
        put :update, params: { id: application.to_param, application: invalid_attributes }, session: valid_session
        application.reload

        expect(application.redirect_uri).not_to eq(invalid_attributes[:redirect_uri])
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested application" do
      application = Doorkeeper::Application.create! valid_attributes
      expect do
        delete :destroy, params: { id: application.to_param }, session: valid_session
      end.to change(Doorkeeper::Application, :count).by(-1)
    end

    it "redirects to the admin_applications list" do
      application = Doorkeeper::Application.create! valid_attributes
      delete :destroy, params: { id: application.to_param }, session: valid_session
      expect(response).to redirect_to(admin_applications_url)
    end
  end
end
