FROM ruby:2.4-alpine
LABEL maintainer="Josh Ashby <me@joshisa.ninja>"

RUN bundle exec rake RAILS_ENV=production DATABASE_URL=postgresql://user:pass@127.0.0.1/dbname assets:precompile

VOLUME ["/app/public", "/dropzone"]

CMD bundle exec puma -C config/puma.rb
