#!/bin/bash
set -ev

./.travis/common

echo "Building API docs"
bundle exec rake docs:generate

echo "Building new assets"
bundle exec rake assets:precompile

export DO_SPACES_ENDPOINT=https://nyc3.digitaloceanspaces.com
export CURRENT_DATE=$(date -u +%FT%H%M%S)
export PACKAGE=package-${CURRENT_DATE}.tar.gz

ls public/

echo "Building package $PACKAGE"
tar -zcvf $PACKAGE public doc
echo $PACKAGE > current_package

echo "Uploading $PACKAGE to DO space"
aws s3 cp $PACKAGE s3://transientbug-assets/ --endpoint $DO_SPACES_ENDPOINT
aws s3 cp current_package s3://transientbug-assets/ --endpoint $DO_SPACES_ENDPOINT
