#!/bin/bash
set -ev

if [ ! -d elasticsearch-${ES_VERSION}/bin ]; then
  echo "Downloading ES ${ES_VERSION}"
  wget "${ES_DOWNLOAD_URL}"
  tar -xzf "elasticsearch-${ES_VERSION}.tar.gz"
fi

echo "Creating test database"
psql -c 'create database travis_ci_test;' -U postgres

echo "Starting ES"
./elasticsearch-${ES_VERSION}/bin/elasticsearch &

echo "Yarn install"
yarn install

echo "Moving CI Master key into place"
mv config/master.ci.key config/master.key

echo "Moving CI Credentials encrypted file into place"
rm config/credentials.yml.enc
mv config/credentials.ci.yml.enc config/credentials.yml.enc

echo "Waiting for ES to finish booting"
wget -q --waitretry=10 --retry-connrefused -T 60 -O - http://127.0.0.1:9200
