#!/bin/bash
set -ev

psql -c 'create database travis_ci_test;' -U postgres

wget ${ES_DOWNLOAD_URL}
tar -xzf elasticsearch-${ES_VERSION}.tar.gz
./elasticsearch-${ES_VERSION}/bin/elasticsearch &

yarn install

wget -q --waitretry=2 --retry-connrefused -T 20 -O - http://127.0.0.1:9200

mv config/master.ci.key config/master.key
rm config/credentials.yml.enc
mv config/credentials.ci.yml.enc config/credentials.yml.enc

bundle exec rspec
