#!/bin/bash
set -ev

if [ ! -d directory ]; then
  wget ${ES_DOWNLOAD_URL}
  tar -xzf elasticsearch-${ES_VERSION}.tar.gz
fi

./elasticsearch-${ES_VERSION}/bin/elasticsearch &

yarn install

wget -q --waitretry=2 --retry-connrefused -T 20 -O - http://127.0.0.1:9200

bundle exec rspec
